### ISSUE TITLE
建议创建一个生成 jshint配置文件的子生成器

### ISSUE THREAD

**Issue by lynzz** [hiwanz/generator-fedp#4]
现 generator-java-webapp 的 jshint配置，无法与 fedp 同步，所以建议，先由 fedp 创建一个子生成器，这样如fedp 有更新 jshint的话，只需通过fedp，重新一份配置即可，

如：
```
yo fedp:jshint jshintrc
```

这样就可同步 jshint 的配置了

**Comment by hiwanz** [comment]
为了保持生成器所有部件都是最新，可以对生成器进行update之后，在原有项目上重新yo一下，选择性覆盖已有文件。
